---

- hosts: spokes

  connection: local
  gather_facts: 'no'


  roles:
    - role: acl
      tags: acl
    - role: crypto
      tags: crypto
    - role: interfaces
      tags: interfaces
    - role: spokes
      tags: spokes